### ISSUE TITLE
Find the app from the Marketplace

### ISSUE THREAD

**Issue by lal1004** [ads1010/Practica2GestPro#46]

**Comment by ads1010** [comment]
Hay que añadir la información de cada producto, a la derecha de las imágenes

**Comment by jzj1001Ubu** [comment]
¿Por otro lado que imágenes vamos a seleccionar para mostrar nuestra app en la marketplace?

**Comment by lal1004** [comment]
Las capturas principales de nuestra aplicación y sus ajustes
